// Generated by cleave. Do not edit.
#include "kuf_stg.h"

namespace kuf_stg {

StgStringParam StgStringParam::parse(const uint8_t* buf, size_t len, size_t& offset) {
    StgStringParam result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.length, buf + offset, 4);
    offset += 4;
    if (offset + result.length > len) throw std::runtime_error("buffer overflow");
    result.value.assign(buf + offset, buf + offset + result.length);
    offset += result.length;
    return result;
}

std::string StgStringParam::to_json() const {
    std::string s = "{";
    s += "\"length\":";
    s += std::to_string(length);
    s += ",";
    s += "\"value\":";
    s += "[";
    for (size_t i = 0; i < value.size(); ++i) {
        if (i > 0) s += ",";
        s += std::to_string(value[i]);
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> StgStringParam::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = static_cast<uint32_t>(value.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.insert(_buf.end(), value.begin(), value.end());
    return _buf;
}

StgHeader StgHeader::parse(const uint8_t* buf, size_t len, size_t& offset) {
    StgHeader result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.reserved_0, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unknown_1, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unknown_2, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unknown_3, buf + offset, 4);
    offset += 4;
    if (offset + 24 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.reserved_1, buf + offset, 24);
    offset += 24;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unknown_4, buf + offset, 4);
    offset += 4;
    if (offset + 24 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.reserved_2, buf + offset, 24);
    offset += 24;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.map_filename, buf + offset, 64);
    offset += 64;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.bitmap_filename, buf + offset, 64);
    offset += 64;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.default_camera, buf + offset, 64);
    offset += 64;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.user_camera, buf + offset, 64);
    offset += 64;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.settings_file, buf + offset, 64);
    offset += 64;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.sky_effects, buf + offset, 64);
    offset += 64;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.ai_script, buf + offset, 64);
    offset += 64;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.padding_208, buf + offset, 4);
    offset += 4;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.cubemap_texture, buf + offset, 64);
    offset += 64;
    if (offset + 36 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.config_data, buf + offset, 36);
    offset += 36;
    return result;
}

std::string StgHeader::to_json() const {
    std::string s = "{";
    s += "\"reserved_0\":";
    s += std::to_string(reserved_0);
    s += ",";
    s += "\"unknown_1\":";
    s += std::to_string(unknown_1);
    s += ",";
    s += "\"unknown_2\":";
    s += std::to_string(unknown_2);
    s += ",";
    s += "\"unknown_3\":";
    s += std::to_string(unknown_3);
    s += ",";
    s += "\"reserved_1\":";
    s += "[";
    for (size_t i = 0; i < 24; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(reserved_1[i]);
    }
    s += "]";
    s += ",";
    s += "\"unknown_4\":";
    s += std::to_string(unknown_4);
    s += ",";
    s += "\"reserved_2\":";
    s += "[";
    for (size_t i = 0; i < 24; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(reserved_2[i]);
    }
    s += "]";
    s += ",";
    s += "\"map_filename\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(map_filename[i]);
    }
    s += "]";
    s += ",";
    s += "\"bitmap_filename\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(bitmap_filename[i]);
    }
    s += "]";
    s += ",";
    s += "\"default_camera\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(default_camera[i]);
    }
    s += "]";
    s += ",";
    s += "\"user_camera\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(user_camera[i]);
    }
    s += "]";
    s += ",";
    s += "\"settings_file\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(settings_file[i]);
    }
    s += "]";
    s += ",";
    s += "\"sky_effects\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(sky_effects[i]);
    }
    s += "]";
    s += ",";
    s += "\"ai_script\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(ai_script[i]);
    }
    s += "]";
    s += ",";
    s += "\"padding_208\":";
    s += "[";
    for (size_t i = 0; i < 4; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(padding_208[i]);
    }
    s += "]";
    s += ",";
    s += "\"cubemap_texture\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(cubemap_texture[i]);
    }
    s += "]";
    s += ",";
    s += "\"config_data\":";
    s += "[";
    for (size_t i = 0; i < 36; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(config_data[i]);
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> StgHeader::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        int32_t _tmp = reserved_0;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = unknown_1;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = unknown_2;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = unknown_3;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.insert(_buf.end(), reserved_1, reserved_1 + 24);
    {
        uint32_t _tmp = unknown_4;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.insert(_buf.end(), reserved_2, reserved_2 + 24);
    _buf.insert(_buf.end(), map_filename, map_filename + 64);
    _buf.insert(_buf.end(), bitmap_filename, bitmap_filename + 64);
    _buf.insert(_buf.end(), default_camera, default_camera + 64);
    _buf.insert(_buf.end(), user_camera, user_camera + 64);
    _buf.insert(_buf.end(), settings_file, settings_file + 64);
    _buf.insert(_buf.end(), sky_effects, sky_effects + 64);
    _buf.insert(_buf.end(), ai_script, ai_script + 64);
    _buf.insert(_buf.end(), padding_208, padding_208 + 4);
    _buf.insert(_buf.end(), cubemap_texture, cubemap_texture + 64);
    _buf.insert(_buf.end(), config_data, config_data + 36);
    return _buf;
}

UnitBlock UnitBlock::parse(const uint8_t* buf, size_t len, size_t& offset) {
    UnitBlock result;
    if (offset + 32 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.name, buf + offset, 32);
    offset += 32;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unique_id, buf + offset, 4);
    offset += 4;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.ucd = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.is_hero = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.is_enabled = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.reserved_27 = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.leader_hp_override, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unit_hp_override, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unknown_30, buf + offset, 4);
    offset += 4;
    if (offset + 16 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.reserved_34, buf + offset, 16);
    offset += 16;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.pos_x, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.pos_y, buf + offset, 4);
    offset += 4;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.facing_direction = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.extra_flags_1 = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.extra_flags_2 = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.category = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.reserved_50, buf + offset, 4);
    offset += 4;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.leader_job_type = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.leader_model_id = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.leader_worldmap_id = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.leader_level = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 8 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.leader_skills, buf + offset, 8);
    offset += 8;
    for (int i = 0; i < 23; ++i) {
        int32_t val;
        if (offset + 4 > len) throw std::runtime_error("buffer overflow");
        std::memcpy(&val, buf + offset, 4);
        offset += 4;
        result.leader_abilities.push_back(val);
    }
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.officer_count, buf + offset, 4);
    offset += 4;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.officer1_job_type = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.officer1_model_id = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.officer1_worldmap_id = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.officer1_level = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 100 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.officer1_data, buf + offset, 100);
    offset += 100;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.officer2_job_type = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.officer2_model_id = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.officer2_worldmap_id = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 1 > len) throw std::runtime_error("buffer overflow");
    result.officer2_level = static_cast<uint8_t>(buf[offset]);
    offset += 1;
    if (offset + 84 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.officer2_data, buf + offset, 84);
    offset += 84;
    if (offset + 12 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.padding_180, buf + offset, 12);
    offset += 12;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.animation_config, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.grid_x, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.grid_y, buf + offset, 4);
    offset += 4;
    if (offset + 40 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.reserved_198, buf + offset, 40);
    offset += 40;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.troop_info_index, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.formation_type, buf + offset, 4);
    offset += 4;
    for (int i = 0; i < 22; ++i) {
        float val;
        if (offset + 4 > len) throw std::runtime_error("buffer overflow");
        std::memcpy(&val, buf + offset, 4);
        offset += 4;
        result.stat_overrides.push_back(val);
    }
    return result;
}

std::string UnitBlock::to_json() const {
    std::string s = "{";
    s += "\"name\":";
    s += "[";
    for (size_t i = 0; i < 32; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(name[i]);
    }
    s += "]";
    s += ",";
    s += "\"unique_id\":";
    s += std::to_string(unique_id);
    s += ",";
    s += "\"ucd\":";
    s += std::to_string(ucd);
    s += ",";
    s += "\"is_hero\":";
    s += std::to_string(is_hero);
    s += ",";
    s += "\"is_enabled\":";
    s += std::to_string(is_enabled);
    s += ",";
    s += "\"reserved_27\":";
    s += std::to_string(reserved_27);
    s += ",";
    s += "\"leader_hp_override\":";
    s += std::to_string(leader_hp_override);
    s += ",";
    s += "\"unit_hp_override\":";
    s += std::to_string(unit_hp_override);
    s += ",";
    s += "\"unknown_30\":";
    s += std::to_string(unknown_30);
    s += ",";
    s += "\"reserved_34\":";
    s += "[";
    for (size_t i = 0; i < 16; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(reserved_34[i]);
    }
    s += "]";
    s += ",";
    s += "\"pos_x\":";
    s += std::to_string(pos_x);
    s += ",";
    s += "\"pos_y\":";
    s += std::to_string(pos_y);
    s += ",";
    s += "\"facing_direction\":";
    s += std::to_string(facing_direction);
    s += ",";
    s += "\"extra_flags_1\":";
    s += std::to_string(extra_flags_1);
    s += ",";
    s += "\"extra_flags_2\":";
    s += std::to_string(extra_flags_2);
    s += ",";
    s += "\"category\":";
    s += std::to_string(category);
    s += ",";
    s += "\"reserved_50\":";
    s += std::to_string(reserved_50);
    s += ",";
    s += "\"leader_job_type\":";
    s += std::to_string(leader_job_type);
    s += ",";
    s += "\"leader_model_id\":";
    s += std::to_string(leader_model_id);
    s += ",";
    s += "\"leader_worldmap_id\":";
    s += std::to_string(leader_worldmap_id);
    s += ",";
    s += "\"leader_level\":";
    s += std::to_string(leader_level);
    s += ",";
    s += "\"leader_skills\":";
    s += "[";
    for (size_t i = 0; i < 8; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(leader_skills[i]);
    }
    s += "]";
    s += ",";
    s += "\"leader_abilities\":";
    s += "[";
    for (size_t i = 0; i < leader_abilities.size(); ++i) {
        if (i > 0) s += ",";
        s += std::to_string(leader_abilities[i]);
    }
    s += "]";
    s += ",";
    s += "\"officer_count\":";
    s += std::to_string(officer_count);
    s += ",";
    s += "\"officer1_job_type\":";
    s += std::to_string(officer1_job_type);
    s += ",";
    s += "\"officer1_model_id\":";
    s += std::to_string(officer1_model_id);
    s += ",";
    s += "\"officer1_worldmap_id\":";
    s += std::to_string(officer1_worldmap_id);
    s += ",";
    s += "\"officer1_level\":";
    s += std::to_string(officer1_level);
    s += ",";
    s += "\"officer1_data\":";
    s += "[";
    for (size_t i = 0; i < 100; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(officer1_data[i]);
    }
    s += "]";
    s += ",";
    s += "\"officer2_job_type\":";
    s += std::to_string(officer2_job_type);
    s += ",";
    s += "\"officer2_model_id\":";
    s += std::to_string(officer2_model_id);
    s += ",";
    s += "\"officer2_worldmap_id\":";
    s += std::to_string(officer2_worldmap_id);
    s += ",";
    s += "\"officer2_level\":";
    s += std::to_string(officer2_level);
    s += ",";
    s += "\"officer2_data\":";
    s += "[";
    for (size_t i = 0; i < 84; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(officer2_data[i]);
    }
    s += "]";
    s += ",";
    s += "\"padding_180\":";
    s += "[";
    for (size_t i = 0; i < 12; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(padding_180[i]);
    }
    s += "]";
    s += ",";
    s += "\"animation_config\":";
    s += std::to_string(animation_config);
    s += ",";
    s += "\"grid_x\":";
    s += std::to_string(grid_x);
    s += ",";
    s += "\"grid_y\":";
    s += std::to_string(grid_y);
    s += ",";
    s += "\"reserved_198\":";
    s += "[";
    for (size_t i = 0; i < 40; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(reserved_198[i]);
    }
    s += "]";
    s += ",";
    s += "\"troop_info_index\":";
    s += std::to_string(troop_info_index);
    s += ",";
    s += "\"formation_type\":";
    s += std::to_string(formation_type);
    s += ",";
    s += "\"stat_overrides\":";
    s += "[";
    for (size_t i = 0; i < stat_overrides.size(); ++i) {
        if (i > 0) s += ",";
        s += std::to_string(stat_overrides[i]);
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> UnitBlock::to_bytes() const {
    std::vector<uint8_t> _buf;
    _buf.insert(_buf.end(), name, name + 32);
    {
        uint32_t _tmp = unique_id;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.push_back(static_cast<uint8_t>(ucd));
    _buf.push_back(static_cast<uint8_t>(is_hero));
    _buf.push_back(static_cast<uint8_t>(is_enabled));
    _buf.push_back(static_cast<uint8_t>(reserved_27));
    {
        float _tmp = leader_hp_override;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        float _tmp = unit_hp_override;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        float _tmp = unknown_30;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.insert(_buf.end(), reserved_34, reserved_34 + 16);
    {
        float _tmp = pos_x;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        float _tmp = pos_y;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.push_back(static_cast<uint8_t>(facing_direction));
    _buf.push_back(static_cast<uint8_t>(extra_flags_1));
    _buf.push_back(static_cast<uint8_t>(extra_flags_2));
    _buf.push_back(static_cast<uint8_t>(category));
    {
        int32_t _tmp = reserved_50;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.push_back(static_cast<uint8_t>(leader_job_type));
    _buf.push_back(static_cast<uint8_t>(leader_model_id));
    _buf.push_back(static_cast<uint8_t>(leader_worldmap_id));
    _buf.push_back(static_cast<uint8_t>(leader_level));
    _buf.insert(_buf.end(), leader_skills, leader_skills + 8);
    for (const auto& _v : leader_abilities) {
        {
            int32_t _tmp = _v;
            uint8_t _raw[4];
            std::memcpy(_raw, &_tmp, 4);
            _buf.insert(_buf.end(), _raw, _raw + 4);
        }
    }
    {
        uint32_t _tmp = officer_count;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.push_back(static_cast<uint8_t>(officer1_job_type));
    _buf.push_back(static_cast<uint8_t>(officer1_model_id));
    _buf.push_back(static_cast<uint8_t>(officer1_worldmap_id));
    _buf.push_back(static_cast<uint8_t>(officer1_level));
    _buf.insert(_buf.end(), officer1_data, officer1_data + 100);
    _buf.push_back(static_cast<uint8_t>(officer2_job_type));
    _buf.push_back(static_cast<uint8_t>(officer2_model_id));
    _buf.push_back(static_cast<uint8_t>(officer2_worldmap_id));
    _buf.push_back(static_cast<uint8_t>(officer2_level));
    _buf.insert(_buf.end(), officer2_data, officer2_data + 84);
    _buf.insert(_buf.end(), padding_180, padding_180 + 12);
    {
        uint32_t _tmp = animation_config;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = grid_x;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = grid_y;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.insert(_buf.end(), reserved_198, reserved_198 + 40);
    {
        int32_t _tmp = troop_info_index;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = formation_type;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _v : stat_overrides) {
        {
            float _tmp = _v;
            uint8_t _raw[4];
            std::memcpy(_raw, &_tmp, 4);
            _buf.insert(_buf.end(), _raw, _raw + 4);
        }
    }
    return _buf;
}

AreaEntry AreaEntry::parse(const uint8_t* buf, size_t len, size_t& offset) {
    AreaEntry result;
    if (offset + 32 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.description, buf + offset, 32);
    offset += 32;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unknown_20, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unknown_24, buf + offset, 4);
    offset += 4;
    if (offset + 24 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.unknown_28, buf + offset, 24);
    offset += 24;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.area_id, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.bound_x1, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.bound_y1, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.bound_x2, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.bound_y2, buf + offset, 4);
    offset += 4;
    return result;
}

std::string AreaEntry::to_json() const {
    std::string s = "{";
    s += "\"description\":";
    s += "[";
    for (size_t i = 0; i < 32; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(description[i]);
    }
    s += "]";
    s += ",";
    s += "\"unknown_20\":";
    s += std::to_string(unknown_20);
    s += ",";
    s += "\"unknown_24\":";
    s += std::to_string(unknown_24);
    s += ",";
    s += "\"unknown_28\":";
    s += "[";
    for (size_t i = 0; i < 24; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(unknown_28[i]);
    }
    s += "]";
    s += ",";
    s += "\"area_id\":";
    s += std::to_string(area_id);
    s += ",";
    s += "\"bound_x1\":";
    s += std::to_string(bound_x1);
    s += ",";
    s += "\"bound_y1\":";
    s += std::to_string(bound_y1);
    s += ",";
    s += "\"bound_x2\":";
    s += std::to_string(bound_x2);
    s += ",";
    s += "\"bound_y2\":";
    s += std::to_string(bound_y2);
    s += "}";
    return s;
}

std::vector<uint8_t> AreaEntry::to_bytes() const {
    std::vector<uint8_t> _buf;
    _buf.insert(_buf.end(), description, description + 32);
    {
        uint32_t _tmp = unknown_20;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = unknown_24;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    _buf.insert(_buf.end(), unknown_28, unknown_28 + 24);
    {
        uint32_t _tmp = area_id;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        float _tmp = bound_x1;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        float _tmp = bound_y1;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        float _tmp = bound_x2;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        float _tmp = bound_y2;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    return _buf;
}

StgParamValue StgParamValue::parse(const uint8_t* buf, size_t len, size_t& offset) {
    StgParamValue result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.type_tag, buf + offset, 4);
    offset += 4;
    if (result.type_tag == 0) {
        auto& _val = result.value.emplace<0>();
        if (offset + 4 > len) throw std::runtime_error("buffer overflow");
        std::memcpy(&_val, buf + offset, 4);
        offset += 4;
    } else if (result.type_tag == 1) {
        auto& _val = result.value.emplace<1>();
        if (offset + 4 > len) throw std::runtime_error("buffer overflow");
        std::memcpy(&_val, buf + offset, 4);
        offset += 4;
    } else if (result.type_tag == 2) {
        result.value.emplace<2>(StgStringParam::parse(buf, len, offset));
    } else if (result.type_tag == 3) {
        auto& _val = result.value.emplace<0>();
        if (offset + 4 > len) throw std::runtime_error("buffer overflow");
        std::memcpy(&_val, buf + offset, 4);
        offset += 4;
    } else {
        throw std::runtime_error("unknown tag value for StgParamValue.value");
    }
    return result;
}

std::string StgParamValue::to_json() const {
    std::string s = "{";
    s += "\"type_tag\":";
    s += std::to_string(type_tag);
    s += ",";
    s += "\"value\":";
    if (value.index() == 0) {
        s += std::to_string(std::get<0>(value));
    } else if (value.index() == 1) {
        s += std::to_string(std::get<1>(value));
    } else if (value.index() == 2) {
        s += std::get<2>(value).to_json();
    } else if (value.index() == 0) {
        s += std::to_string(std::get<0>(value));
    }
    s += "}";
    return s;
}

std::vector<uint8_t> StgParamValue::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = type_tag;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    if (value.index() == 0) {
        auto& _v = std::get<0>(value);
        int32_t _tmp = _v;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    } else if (value.index() == 1) {
        auto& _v = std::get<1>(value);
        float _tmp = _v;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    } else if (value.index() == 2) {
        auto _tmp = std::get<2>(value).to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    } else if (value.index() == 0) {
        auto& _v = std::get<0>(value);
        int32_t _tmp = _v;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    return _buf;
}

StgVariable StgVariable::parse(const uint8_t* buf, size_t len, size_t& offset) {
    StgVariable result;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.name, buf + offset, 64);
    offset += 64;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.variable_id, buf + offset, 4);
    offset += 4;
    result.initial_value = StgParamValue::parse(buf, len, offset);
    return result;
}

std::string StgVariable::to_json() const {
    std::string s = "{";
    s += "\"name\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(name[i]);
    }
    s += "]";
    s += ",";
    s += "\"variable_id\":";
    s += std::to_string(variable_id);
    s += ",";
    s += "\"initial_value\":";
    s += initial_value.to_json();
    s += "}";
    return s;
}

std::vector<uint8_t> StgVariable::to_bytes() const {
    std::vector<uint8_t> _buf;
    _buf.insert(_buf.end(), name, name + 64);
    {
        uint32_t _tmp = variable_id;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        auto _tmp = initial_value.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    return _buf;
}

StgCondition StgCondition::parse(const uint8_t* buf, size_t len, size_t& offset) {
    StgCondition result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.type_id, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.param_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.param_count; ++i) {
        result.params.push_back(StgParamValue::parse(buf, len, offset));
    }
    return result;
}

std::string StgCondition::to_json() const {
    std::string s = "{";
    s += "\"type_id\":";
    s += std::to_string(type_id);
    s += ",";
    s += "\"param_count\":";
    s += std::to_string(param_count);
    s += ",";
    s += "\"params\":";
    s += "[";
    for (size_t i = 0; i < params.size(); ++i) {
        if (i > 0) s += ",";
        s += params[i].to_json();
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> StgCondition::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = type_id;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(params.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : params) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    return _buf;
}

StgAction StgAction::parse(const uint8_t* buf, size_t len, size_t& offset) {
    StgAction result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.type_id, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.param_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.param_count; ++i) {
        result.params.push_back(StgParamValue::parse(buf, len, offset));
    }
    return result;
}

std::string StgAction::to_json() const {
    std::string s = "{";
    s += "\"type_id\":";
    s += std::to_string(type_id);
    s += ",";
    s += "\"param_count\":";
    s += std::to_string(param_count);
    s += ",";
    s += "\"params\":";
    s += "[";
    for (size_t i = 0; i < params.size(); ++i) {
        if (i > 0) s += ",";
        s += params[i].to_json();
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> StgAction::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = type_id;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(params.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : params) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    return _buf;
}

StgEvent StgEvent::parse(const uint8_t* buf, size_t len, size_t& offset) {
    StgEvent result;
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.description, buf + offset, 64);
    offset += 64;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.event_id, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.condition_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.condition_count; ++i) {
        result.conditions.push_back(StgCondition::parse(buf, len, offset));
    }
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.action_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.action_count; ++i) {
        result.actions.push_back(StgAction::parse(buf, len, offset));
    }
    return result;
}

std::string StgEvent::to_json() const {
    std::string s = "{";
    s += "\"description\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(description[i]);
    }
    s += "]";
    s += ",";
    s += "\"event_id\":";
    s += std::to_string(event_id);
    s += ",";
    s += "\"condition_count\":";
    s += std::to_string(condition_count);
    s += ",";
    s += "\"conditions\":";
    s += "[";
    for (size_t i = 0; i < conditions.size(); ++i) {
        if (i > 0) s += ",";
        s += conditions[i].to_json();
    }
    s += "]";
    s += ",";
    s += "\"action_count\":";
    s += std::to_string(action_count);
    s += ",";
    s += "\"actions\":";
    s += "[";
    for (size_t i = 0; i < actions.size(); ++i) {
        if (i > 0) s += ",";
        s += actions[i].to_json();
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> StgEvent::to_bytes() const {
    std::vector<uint8_t> _buf;
    _buf.insert(_buf.end(), description, description + 64);
    {
        uint32_t _tmp = event_id;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(conditions.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : conditions) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(actions.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : actions) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    return _buf;
}

EventBlock EventBlock::parse(const uint8_t* buf, size_t len, size_t& offset) {
    EventBlock result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.block_header, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.event_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.event_count; ++i) {
        result.events.push_back(StgEvent::parse(buf, len, offset));
    }
    return result;
}

std::string EventBlock::to_json() const {
    std::string s = "{";
    s += "\"block_header\":";
    s += std::to_string(block_header);
    s += ",";
    s += "\"event_count\":";
    s += std::to_string(event_count);
    s += ",";
    s += "\"events\":";
    s += "[";
    for (size_t i = 0; i < events.size(); ++i) {
        if (i > 0) s += ",";
        s += events[i].to_json();
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> EventBlock::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = block_header;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(events.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : events) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    return _buf;
}

FooterEntry FooterEntry::parse(const uint8_t* buf, size_t len, size_t& offset) {
    FooterEntry result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.slot_data_1, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.slot_data_2, buf + offset, 4);
    offset += 4;
    return result;
}

std::string FooterEntry::to_json() const {
    std::string s = "{";
    s += "\"slot_data_1\":";
    s += std::to_string(slot_data_1);
    s += ",";
    s += "\"slot_data_2\":";
    s += std::to_string(slot_data_2);
    s += "}";
    return s;
}

std::vector<uint8_t> FooterEntry::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = slot_data_1;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = slot_data_2;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    return _buf;
}

File File::parse(const uint8_t* buf, size_t len, size_t& offset) {
    File result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.magic, buf + offset, 4);
    offset += 4;
    if (!((result.magic == 1001))) {
        throw std::runtime_error("STG magic must be 0x3E9");
    }
    result.header = StgHeader::parse(buf, len, offset);
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.unit_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.unit_count; ++i) {
        result.units.push_back(UnitBlock::parse(buf, len, offset));
    }
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.area_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.area_count; ++i) {
        result.areas.push_back(AreaEntry::parse(buf, len, offset));
    }
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.variable_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.variable_count; ++i) {
        result.variables.push_back(StgVariable::parse(buf, len, offset));
    }
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.event_block_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.event_block_count; ++i) {
        result.event_blocks.push_back(EventBlock::parse(buf, len, offset));
    }
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.footer_count, buf + offset, 4);
    offset += 4;
    for (size_t i = 0; i < result.footer_count; ++i) {
        result.footer_entries.push_back(FooterEntry::parse(buf, len, offset));
    }
    return result;
}

std::string File::to_json() const {
    std::string s = "{";
    s += "\"magic\":";
    s += std::to_string(magic);
    s += ",";
    s += "\"header\":";
    s += header.to_json();
    s += ",";
    s += "\"unit_count\":";
    s += std::to_string(unit_count);
    s += ",";
    s += "\"units\":";
    s += "[";
    for (size_t i = 0; i < units.size(); ++i) {
        if (i > 0) s += ",";
        s += units[i].to_json();
    }
    s += "]";
    s += ",";
    s += "\"area_count\":";
    s += std::to_string(area_count);
    s += ",";
    s += "\"areas\":";
    s += "[";
    for (size_t i = 0; i < areas.size(); ++i) {
        if (i > 0) s += ",";
        s += areas[i].to_json();
    }
    s += "]";
    s += ",";
    s += "\"variable_count\":";
    s += std::to_string(variable_count);
    s += ",";
    s += "\"variables\":";
    s += "[";
    for (size_t i = 0; i < variables.size(); ++i) {
        if (i > 0) s += ",";
        s += variables[i].to_json();
    }
    s += "]";
    s += ",";
    s += "\"event_block_count\":";
    s += std::to_string(event_block_count);
    s += ",";
    s += "\"event_blocks\":";
    s += "[";
    for (size_t i = 0; i < event_blocks.size(); ++i) {
        if (i > 0) s += ",";
        s += event_blocks[i].to_json();
    }
    s += "]";
    s += ",";
    s += "\"footer_count\":";
    s += std::to_string(footer_count);
    s += ",";
    s += "\"footer_entries\":";
    s += "[";
    for (size_t i = 0; i < footer_entries.size(); ++i) {
        if (i > 0) s += ",";
        s += footer_entries[i].to_json();
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> File::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = magic;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        auto _tmp = header.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(units.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : units) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(areas.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : areas) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(variables.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : variables) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(event_blocks.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : event_blocks) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    {
        uint32_t _tmp = static_cast<uint32_t>(footer_entries.size());
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _item : footer_entries) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    return _buf;
}

} // namespace kuf_stg
