// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
#include <stdexcept>

namespace kuf_save {

struct UnitSaveData {
    uint32_t unknown_index;
    uint32_t troop_info_index;
    uint32_t job_type;
    uint32_t model_id;
    uint32_t stg_field_190;
    uint32_t stg_field_192;
    uint32_t stg_field_194;
    uint32_t stg_field_198;
    uint32_t char_id;
    uint32_t troop_info_index_2;
    uint32_t ucd;
    uint32_t formation_type;
    uint32_t grid_config;
    uint32_t skill_level;
    uint8_t byte_58;
    uint8_t hero_flag;
    uint8_t byte_5a;
    uint32_t field_60;
    uint32_t field_64;
    uint32_t field_68;
    uint8_t equipment[24];
    uint8_t leader_abilities_1[64];
    uint8_t officer1_abilities_1[64];
    uint8_t officer2_abilities_1[64];
    uint8_t leader_abilities_2[64];
    uint8_t officer1_abilities_2[64];
    uint8_t officer2_abilities_2[64];
    uint32_t field_504;

    static UnitSaveData parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct RosterEntry {
    uint8_t byte_61;
    uint8_t byte_60;
    uint8_t byte_62;
    uint8_t byte_63;
    uint32_t uint_64;

    static RosterEntry parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct File {
    uint32_t size_prefix;
    uint32_t magic;
    uint8_t context_data[1080];
    uint32_t campaign_index;
    uint8_t main_save_block[340];
    uint32_t unit_count;
    std::vector<UnitSaveData> units;
    uint32_t selected_unit_ref;
    uint32_t roster_count;
    std::vector<RosterEntry> roster_entries;
    uint32_t second_array_count;
    std::vector<uint32_t> second_array;
    std::vector<uint32_t> mission_completion;
    uint32_t current_mission_slot;
    std::vector<uint8_t> tail_data;

    static File parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

} // namespace kuf_save
