// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
#include <stdexcept>

namespace sox_unit_uv_info {

struct SoxHeader {
    uint32_t marker;
    uint32_t record_count;

    static SoxHeader parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct Lps {
    uint16_t length;
    std::vector<uint8_t> value;

    static Lps parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct UnitUvInfoRecord {
    uint32_t unknown_0;
    uint32_t base_value;
    uint32_t uv_offset_x;
    uint32_t uv_offset_y;
    uint32_t uv_scale;
    uint32_t anim_frame_data;
    uint32_t anim_timing;
    uint32_t frame_count;
    uint32_t unknown_8;

    static UnitUvInfoRecord parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct File {
    SoxHeader header;
    std::vector<UnitUvInfoRecord> records;
    uint8_t footer[64];

    static File parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

} // namespace sox_unit_uv_info
