// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
#include <stdexcept>

namespace sox_library_info {

struct SoxHeader {
    uint32_t marker;
    uint32_t record_count;

    static SoxHeader parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct Lps {
    uint16_t length;
    std::vector<uint8_t> value;

    static Lps parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct LibraryInfoRecord {
    uint32_t data_offset;
    uint16_t unknown;

    static LibraryInfoRecord parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct File {
    SoxHeader header;
    std::vector<LibraryInfoRecord> records;
    uint8_t footer[64];

    static File parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

} // namespace sox_library_info
