// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

namespace sox_char_info {

struct SoxHeader {
	uint32_t marker;
	uint32_t record_count;

	static SoxHeader parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct CharInfoRecord {
	uint32_t character_id;
	int32_t animation_id;
	int32_t model_id_variant;
	int32_t unknown_03;
	uint32_t max_hp;
	uint32_t hero_class;
	uint32_t unknown_hp_field;
	uint32_t unknown_07;
	uint32_t unknown_08;
	uint32_t base_stat_value;
	uint32_t unknown_10;
	uint32_t unknown_11;
	std::vector<uint32_t> combat_stats;
	std::vector<int32_t> skill_ability_slots;
	std::vector<int32_t> additional_ability_slots;
	uint32_t unknown_footer;

	static CharInfoRecord parse(const uint8_t *buf, size_t len,
				    size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct File {
	SoxHeader header;
	std::vector<CharInfoRecord> records;
	uint8_t footer[64];

	static File parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

} // namespace sox_char_info
