// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

namespace sox_job_info {

struct Lps {
	uint16_t length;
	std::vector<uint8_t> value;

	static Lps parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct SoxHeader {
	uint32_t marker;
	uint32_t record_count;

	static SoxHeader parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct JobInfoRecord {
	uint32_t job_id;
	uint32_t field_1;
	uint32_t field_2;
	std::vector<int32_t> stat_fields;
	int32_t skill_0_id;
	int32_t skill_0_bonus;
	int32_t skill_1_id;
	int32_t skill_1_bonus;
	int32_t skill_2_id;
	int32_t skill_2_bonus;
	Lps loc_key;
	Lps icon;

	static JobInfoRecord parse(const uint8_t *buf, size_t len,
				   size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct File {
	SoxHeader header;
	std::vector<JobInfoRecord> records;
	uint8_t footer[64];

	static File parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

} // namespace sox_job_info
