// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

namespace sox_custom_random_table {

struct SoxHeader {
	uint32_t marker;
	uint32_t record_count;

	static SoxHeader parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct Lps {
	uint16_t length;
	std::vector<uint8_t> value;

	static Lps parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct LookupEntry {
	uint32_t field_0;
	uint32_t field_1;
	uint32_t field_2;
	uint32_t field_3;

	static LookupEntry parse(const uint8_t *buf, size_t len,
				 size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct RandomTableRecord {
	uint32_t field_0;
	uint32_t field_1;
	uint32_t field_2;
	uint32_t field_3;
	uint32_t field_4;
	uint32_t field_5;
	std::vector<uint32_t> table_slots;

	static RandomTableRecord parse(const uint8_t *buf, size_t len,
				       size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct File {
	SoxHeader header;
	Lps header_string_0;
	Lps header_string_1;
	LookupEntry lookup_entries;
	uint32_t separator;
	RandomTableRecord records;
	uint8_t footer[64];

	static File parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

} // namespace sox_custom_random_table
