// Generated by cleave. Do not edit.
#include "sox_troop_info.h"

namespace sox_troop_info {

SoxHeader SoxHeader::parse(const uint8_t *buf, size_t len, size_t &offset) {
	SoxHeader result;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.marker, buf + offset, 4);
	offset += 4;
	if (!((result.marker == 100))) {
		throw std::runtime_error("SOX marker must be 100");
	}
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.record_count, buf + offset, 4);
	offset += 4;
	return result;
}

std::string SoxHeader::to_json() const {
	std::string s = "{";
	s += "\"marker\":";
	s += std::to_string(marker);
	s += ",";
	s += "\"record_count\":";
	s += std::to_string(record_count);
	s += "}";
	return s;
}

std::vector<uint8_t> SoxHeader::to_bytes() const {
	std::vector<uint8_t> _buf;
	{
		uint32_t _tmp = marker;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		uint32_t _tmp = record_count;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	return _buf;
}

TroopInfoRecord TroopInfoRecord::parse(const uint8_t *buf, size_t len,
				       size_t &offset) {
	TroopInfoRecord result;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.job, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.type_id, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.move_speed, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.rotate_rate, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.move_acceleration, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.move_deceleration, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.sight_range, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.attack_range_max, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.attack_range_min, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.attack_front_range, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.direct_attack, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.indirect_attack, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.defense, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.base_width, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_melee, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_ranged, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_frontal, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_explosion, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_fire, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_ice, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_lightning, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_holy, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_curse, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.resist_earth, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.max_unit_speed_multiplier, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.default_unit_hp, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.formation_random, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.default_unit_num_x, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.default_unit_num_y, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.unit_hp_level_up, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.level_up_0_skill_id, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.level_up_0_bonus, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.level_up_1_skill_id, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.level_up_1_bonus, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.level_up_2_skill_id, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.level_up_2_bonus, buf + offset, 4);
	offset += 4;
	if (offset + 4 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(&result.damage_distribution, buf + offset, 4);
	offset += 4;
	return result;
}

std::string TroopInfoRecord::to_json() const {
	std::string s = "{";
	s += "\"job\":";
	s += std::to_string(job);
	s += ",";
	s += "\"type_id\":";
	s += std::to_string(type_id);
	s += ",";
	s += "\"move_speed\":";
	s += std::to_string(move_speed);
	s += ",";
	s += "\"rotate_rate\":";
	s += std::to_string(rotate_rate);
	s += ",";
	s += "\"move_acceleration\":";
	s += std::to_string(move_acceleration);
	s += ",";
	s += "\"move_deceleration\":";
	s += std::to_string(move_deceleration);
	s += ",";
	s += "\"sight_range\":";
	s += std::to_string(sight_range);
	s += ",";
	s += "\"attack_range_max\":";
	s += std::to_string(attack_range_max);
	s += ",";
	s += "\"attack_range_min\":";
	s += std::to_string(attack_range_min);
	s += ",";
	s += "\"attack_front_range\":";
	s += std::to_string(attack_front_range);
	s += ",";
	s += "\"direct_attack\":";
	s += std::to_string(direct_attack);
	s += ",";
	s += "\"indirect_attack\":";
	s += std::to_string(indirect_attack);
	s += ",";
	s += "\"defense\":";
	s += std::to_string(defense);
	s += ",";
	s += "\"base_width\":";
	s += std::to_string(base_width);
	s += ",";
	s += "\"resist_melee\":";
	s += std::to_string(resist_melee);
	s += ",";
	s += "\"resist_ranged\":";
	s += std::to_string(resist_ranged);
	s += ",";
	s += "\"resist_frontal\":";
	s += std::to_string(resist_frontal);
	s += ",";
	s += "\"resist_explosion\":";
	s += std::to_string(resist_explosion);
	s += ",";
	s += "\"resist_fire\":";
	s += std::to_string(resist_fire);
	s += ",";
	s += "\"resist_ice\":";
	s += std::to_string(resist_ice);
	s += ",";
	s += "\"resist_lightning\":";
	s += std::to_string(resist_lightning);
	s += ",";
	s += "\"resist_holy\":";
	s += std::to_string(resist_holy);
	s += ",";
	s += "\"resist_curse\":";
	s += std::to_string(resist_curse);
	s += ",";
	s += "\"resist_earth\":";
	s += std::to_string(resist_earth);
	s += ",";
	s += "\"max_unit_speed_multiplier\":";
	s += std::to_string(max_unit_speed_multiplier);
	s += ",";
	s += "\"default_unit_hp\":";
	s += std::to_string(default_unit_hp);
	s += ",";
	s += "\"formation_random\":";
	s += std::to_string(formation_random);
	s += ",";
	s += "\"default_unit_num_x\":";
	s += std::to_string(default_unit_num_x);
	s += ",";
	s += "\"default_unit_num_y\":";
	s += std::to_string(default_unit_num_y);
	s += ",";
	s += "\"unit_hp_level_up\":";
	s += std::to_string(unit_hp_level_up);
	s += ",";
	s += "\"level_up_0_skill_id\":";
	s += std::to_string(level_up_0_skill_id);
	s += ",";
	s += "\"level_up_0_bonus\":";
	s += std::to_string(level_up_0_bonus);
	s += ",";
	s += "\"level_up_1_skill_id\":";
	s += std::to_string(level_up_1_skill_id);
	s += ",";
	s += "\"level_up_1_bonus\":";
	s += std::to_string(level_up_1_bonus);
	s += ",";
	s += "\"level_up_2_skill_id\":";
	s += std::to_string(level_up_2_skill_id);
	s += ",";
	s += "\"level_up_2_bonus\":";
	s += std::to_string(level_up_2_bonus);
	s += ",";
	s += "\"damage_distribution\":";
	s += std::to_string(damage_distribution);
	s += "}";
	return s;
}

std::vector<uint8_t> TroopInfoRecord::to_bytes() const {
	std::vector<uint8_t> _buf;
	{
		int32_t _tmp = job;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = type_id;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = move_speed;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = rotate_rate;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = move_acceleration;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = move_deceleration;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = sight_range;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = attack_range_max;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = attack_range_min;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = attack_front_range;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = direct_attack;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = indirect_attack;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = defense;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = base_width;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_melee;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_ranged;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_frontal;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_explosion;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_fire;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_ice;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_lightning;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_holy;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_curse;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = resist_earth;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = max_unit_speed_multiplier;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = default_unit_hp;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = formation_random;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = default_unit_num_x;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = default_unit_num_y;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = unit_hp_level_up;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = level_up_0_skill_id;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = level_up_0_bonus;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = level_up_1_skill_id;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = level_up_1_bonus;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = level_up_2_skill_id;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = level_up_2_bonus;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	{
		int32_t _tmp = damage_distribution;
		uint8_t _raw[4];
		std::memcpy(_raw, &_tmp, 4);
		_buf.insert(_buf.end(), _raw, _raw + 4);
	}
	return _buf;
}

File File::parse(const uint8_t *buf, size_t len, size_t &offset) {
	File result;
	result.header = SoxHeader::parse(buf, len, offset);
	for (size_t i = 0; i < result.header.record_count; ++i) {
		result.records.push_back(
		    TroopInfoRecord::parse(buf, len, offset));
	}
	if (offset + 64 > len) throw std::runtime_error("buffer overflow");
	std::memcpy(result.footer, buf + offset, 64);
	offset += 64;
	return result;
}

std::string File::to_json() const {
	std::string s = "{";
	s += "\"header\":";
	s += header.to_json();
	s += ",";
	s += "\"records\":";
	s += "[";
	for (size_t i = 0; i < records.size(); ++i) {
		if (i > 0) s += ",";
		s += records[i].to_json();
	}
	s += "]";
	s += ",";
	s += "\"footer\":";
	s += "[";
	for (size_t i = 0; i < 64; ++i) {
		if (i > 0) s += ",";
		s += std::to_string(footer[i]);
	}
	s += "]";
	s += "}";
	return s;
}

std::vector<uint8_t> File::to_bytes() const {
	std::vector<uint8_t> _buf;
	{
		auto _tmp = header.to_bytes();
		_buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
	}
	for (const auto &_item : records) {
		auto _tmp = _item.to_bytes();
		_buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
	}
	_buf.insert(_buf.end(), footer, footer + 64);
	return _buf;
}

} // namespace sox_troop_info
