// Generated by cleave. Do not edit.
#include "sox_leader_generation.h"

namespace sox_leader_generation {

SoxHeader SoxHeader::parse(const uint8_t* buf, size_t len, size_t& offset) {
    SoxHeader result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.marker, buf + offset, 4);
    offset += 4;
    if (!((result.marker == 100))) {
        throw std::runtime_error("SOX marker must be 100");
    }
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.record_count, buf + offset, 4);
    offset += 4;
    return result;
}

std::string SoxHeader::to_json() const {
    std::string s = "{";
    s += "\"marker\":";
    s += std::to_string(marker);
    s += ",";
    s += "\"record_count\":";
    s += std::to_string(record_count);
    s += "}";
    return s;
}

std::vector<uint8_t> SoxHeader::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = marker;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = record_count;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    return _buf;
}

Lps Lps::parse(const uint8_t* buf, size_t len, size_t& offset) {
    Lps result;
    if (offset + 2 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.length, buf + offset, 2);
    offset += 2;
    if (offset + result.length > len) throw std::runtime_error("buffer overflow");
    result.value.assign(buf + offset, buf + offset + result.length);
    offset += result.length;
    return result;
}

std::string Lps::to_json() const {
    std::string s = "{";
    s += "\"length\":";
    s += std::to_string(length);
    s += ",";
    s += "\"value\":";
    s += "[";
    for (size_t i = 0; i < value.size(); ++i) {
        if (i > 0) s += ",";
        s += std::to_string(value[i]);
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> Lps::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint16_t _tmp = static_cast<uint16_t>(value.size());
        uint8_t _raw[2];
        std::memcpy(_raw, &_tmp, 2);
        _buf.insert(_buf.end(), _raw, _raw + 2);
    }
    _buf.insert(_buf.end(), value.begin(), value.end());
    return _buf;
}

LeaderGenerationRecord LeaderGenerationRecord::parse(const uint8_t* buf, size_t len, size_t& offset) {
    LeaderGenerationRecord result;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.template_id, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.faction_type, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.base_stat, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.stat_modifier, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.attribute_1, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.attribute_2, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.attribute_3, buf + offset, 4);
    offset += 4;
    if (offset + 4 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(&result.reserved, buf + offset, 4);
    offset += 4;
    for (int i = 0; i < 10; ++i) {
        int32_t val;
        if (offset + 4 > len) throw std::runtime_error("buffer overflow");
        std::memcpy(&val, buf + offset, 4);
        offset += 4;
        result.ability_equipment_slots.push_back(val);
    }
    return result;
}

std::string LeaderGenerationRecord::to_json() const {
    std::string s = "{";
    s += "\"template_id\":";
    s += std::to_string(template_id);
    s += ",";
    s += "\"faction_type\":";
    s += std::to_string(faction_type);
    s += ",";
    s += "\"base_stat\":";
    s += std::to_string(base_stat);
    s += ",";
    s += "\"stat_modifier\":";
    s += std::to_string(stat_modifier);
    s += ",";
    s += "\"attribute_1\":";
    s += std::to_string(attribute_1);
    s += ",";
    s += "\"attribute_2\":";
    s += std::to_string(attribute_2);
    s += ",";
    s += "\"attribute_3\":";
    s += std::to_string(attribute_3);
    s += ",";
    s += "\"reserved\":";
    s += std::to_string(reserved);
    s += ",";
    s += "\"ability_equipment_slots\":";
    s += "[";
    for (size_t i = 0; i < ability_equipment_slots.size(); ++i) {
        if (i > 0) s += ",";
        s += std::to_string(ability_equipment_slots[i]);
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> LeaderGenerationRecord::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        uint32_t _tmp = template_id;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = faction_type;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = base_stat;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = stat_modifier;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = attribute_1;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = attribute_2;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = attribute_3;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    {
        uint32_t _tmp = reserved;
        uint8_t _raw[4];
        std::memcpy(_raw, &_tmp, 4);
        _buf.insert(_buf.end(), _raw, _raw + 4);
    }
    for (const auto& _v : ability_equipment_slots) {
        {
            int32_t _tmp = _v;
            uint8_t _raw[4];
            std::memcpy(_raw, &_tmp, 4);
            _buf.insert(_buf.end(), _raw, _raw + 4);
        }
    }
    return _buf;
}

File File::parse(const uint8_t* buf, size_t len, size_t& offset) {
    File result;
    result.header = SoxHeader::parse(buf, len, offset);
    for (size_t i = 0; i < result.header.record_count; ++i) {
        result.records.push_back(LeaderGenerationRecord::parse(buf, len, offset));
    }
    if (offset + 64 > len) throw std::runtime_error("buffer overflow");
    std::memcpy(result.footer, buf + offset, 64);
    offset += 64;
    return result;
}

std::string File::to_json() const {
    std::string s = "{";
    s += "\"header\":";
    s += header.to_json();
    s += ",";
    s += "\"records\":";
    s += "[";
    for (size_t i = 0; i < records.size(); ++i) {
        if (i > 0) s += ",";
        s += records[i].to_json();
    }
    s += "]";
    s += ",";
    s += "\"footer\":";
    s += "[";
    for (size_t i = 0; i < 64; ++i) {
        if (i > 0) s += ",";
        s += std::to_string(footer[i]);
    }
    s += "]";
    s += "}";
    return s;
}

std::vector<uint8_t> File::to_bytes() const {
    std::vector<uint8_t> _buf;
    {
        auto _tmp = header.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    for (const auto& _item : records) {
        auto _tmp = _item.to_bytes();
        _buf.insert(_buf.end(), _tmp.begin(), _tmp.end());
    }
    _buf.insert(_buf.end(), footer, footer + 64);
    return _buf;
}

} // namespace sox_leader_generation
