// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

namespace sox_resist_info {

enum class ResistType : int32_t {
	NONE = -1,
	Melee = 0,
	Ranged = 1,
	Explosion = 2,
	Frontal = 3,
	Fire = 4,
	Lightning = 5,
	Ice = 6,
	Holy = 7,
	Poison = 8,
	Curse = 9,
};

struct Lps {
	uint16_t length;
	std::vector<uint8_t> value;

	static Lps parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct SoxHeader {
	uint32_t marker;
	uint32_t record_count;

	static SoxHeader parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct ResistInfoRecord {
	uint32_t resist_id;
	uint32_t unknown;
	Lps loc_key;
	Lps icon;

	static ResistInfoRecord parse(const uint8_t *buf, size_t len,
				      size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

struct File {
	SoxHeader header;
	std::vector<ResistInfoRecord> records;
	uint8_t footer[64];

	static File parse(const uint8_t *buf, size_t len, size_t &offset);
	std::string to_json() const;
	std::vector<uint8_t> to_bytes() const;
};

} // namespace sox_resist_info
