// Generated by cleave. Do not edit.
#pragma once

#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
#include <stdexcept>

namespace sox_ability_by_job {

struct SoxHeader {
    uint32_t marker;
    uint32_t record_count;

    static SoxHeader parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct AbilityByJobRecord {
    uint32_t job_id;
    std::vector<int32_t> ability_slots;

    static AbilityByJobRecord parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

struct File {
    SoxHeader header;
    std::vector<AbilityByJobRecord> records;
    uint8_t footer[64];

    static File parse(const uint8_t* buf, size_t len, size_t& offset);
    std::string to_json() const;
    std::vector<uint8_t> to_bytes() const;
};

} // namespace sox_ability_by_job
