#pragma once

#include <cstddef>
#include <cstdint>

namespace kuf {

struct ScriptEntryInfo {
    uint32_t id;
    const char* name;
    uint32_t paramCount;
    const char* paramNames[3];
};

inline constexpr ScriptEntryInfo kConditions[] = {
    {0,  "CON_STAGE_START",          0, {"", "", ""}},
    {1,  "CON_ALL_DEAD",             1, {"TroopID", "", ""}},
    {2,  "CON_LEADER_DEAD",          1, {"TroopID", "", ""}},
    {3,  "CON_HP_UNDER",             2, {"TroopID", "Percent", ""}},
    {4,  "CON_TROOP_NUM_UNDER",      2, {"TroopID", "Count", ""}},
    {5,  "CON_AREA",                 2, {"TroopID", "AreaID", ""}},
    {6,  "CON_TIME_ELAPSED",         1, {"Seconds", "", ""}},
    {7,  "CON_ITEM_GET",             1, {"ItemID", "", ""}},
    {8,  "CON_ALL_AREA",             1, {"AreaID", "", ""}},
    {9,  "CON_TROOP_NEAR",           3, {"TroopID1", "TroopID2", "Distance"}},
    {10, "CON_TROOP_ATTACK",         2, {"AttackerID", "TargetID", ""}},
    {11, "CON_OBJECT_DEAD",          1, {"ObjectID", "", ""}},
    {12, "CON_TROOP_NOT_AREA",       2, {"TroopID", "AreaID", ""}},
    {13, "CON_ANY_DEAD",             1, {"TroopID", "", ""}},
    {14, "CON_LEADER_HP_UNDER",      2, {"TroopID", "Percent", ""}},
    {15, "CON_ALL_TROOP_NEAR",       2, {"TroopID", "AreaID", ""}},
    {16, "CON_EVENT_TRIGGERED",      1, {"EventID", "", ""}},
    {17, "CON_TROOP_HERO",           1, {"TroopID", "", ""}},
    {18, "CON_OBJECT_HP_UNDER",      2, {"ObjectID", "Percent", ""}},
    {19, "CON_VAR_INT_COMPARE",      3, {"VariableID", "Value", "Compare"}},
    {20, "CON_TROOP_EXIST",          1, {"TroopID", "", ""}},
};

inline constexpr ScriptEntryInfo kActions[] = {
    {0,  "ACT_NONE",                     0, {"", "", ""}},
    {1,  "ACT_CREATE_TROOP",             1, {"TroopID", "", ""}},
    {2,  "ACT_KILL_TROOP",               1, {"TroopID", "", ""}},
    {3,  "ACT_MISSION_WIN",              0, {"", "", ""}},
    {4,  "ACT_MISSION_LOSE",             0, {"", "", ""}},
    {5,  "ACT_MISSION_DRAW",             0, {"", "", ""}},
    {6,  "ACT_SHOW_MESSAGE",             1, {"MessageID", "", ""}},
    {7,  "ACT_CHANGE_SIDE",              2, {"TroopID", "Side", ""}},
    {8,  "ACT_SET_TARGET",               2, {"TroopID", "TargetID", ""}},
    {9,  "ACT_MOVE_TO_AREA",             2, {"TroopID", "AreaID", ""}},
    {10, "ACT_SET_FORMATION",            2, {"TroopID", "Formation", ""}},
    {11, "ACT_SET_AI",                   2, {"TroopID", "AIID", ""}},
    {12, "ACT_PLAY_MOVIE",               1, {"MovieID", "", ""}},
    {13, "ACT_PLAY_SOUND",               1, {"SoundID", "", ""}},
    {14, "ACT_SET_CAMERA",               1, {"CameraID", "", ""}},
    {15, "ACT_SPAWN_OBJECT",             1, {"ObjectID", "", ""}},
    {16, "ACT_DESTROY_OBJECT",           1, {"ObjectID", "", ""}},
    {17, "ACT_SET_WEATHER",              1, {"WeatherID", "", ""}},
    {18, "ACT_SHOW_TUTORIAL",            1, {"TutorialID", "", ""}},
    {19, "ACT_ENABLE_TROOP",             1, {"TroopID", "", ""}},
    {20, "ACT_DISABLE_TROOP",            1, {"TroopID", "", ""}},
    {21, "ACT_SET_HERO_SKILL",           3, {"TroopID", "SkillID", "Level"}},
    {22, "ACT_ADD_ITEM",                 1, {"ItemID", "", ""}},
    {23, "ACT_REMOVE_ITEM",              1, {"ItemID", "", ""}},
    {24, "ACT_SET_TROOP_POS",            3, {"TroopID", "X", "Y"}},
    {25, "ACT_SET_AGGRO",                2, {"TroopID", "TargetID", ""}},
    {26, "ACT_CHANGE_MAP",               1, {"MapID", "", ""}},
    {27, "ACT_FULL_HEAL",                1, {"TroopID", "", ""}},
    {28, "ACT_SET_SPEED",                2, {"TroopID", "Speed", ""}},
    {29, "ACT_PLAY_BGM",                 1, {"BGMID", "", ""}},
    {30, "ACT_STOP_BGM",                 0, {"", "", ""}},
    {31, "ACT_SCREEN_EFFECT",            1, {"EffectID", "", ""}},
    {32, "ACT_PAUSE_AI",                 1, {"TroopID", "", ""}},
    {33, "ACT_RESUME_AI",                1, {"TroopID", "", ""}},
    {34, "ACT_SET_PATROL",               2, {"TroopID", "AreaID", ""}},
    {35, "ACT_SET_GUARD",                2, {"TroopID", "AreaID", ""}},
    {36, "ACT_SET_RETREAT",              2, {"TroopID", "AreaID", ""}},
    {37, "ACT_RALLY_TROOP",              2, {"TroopID", "AreaID", ""}},
    {38, "ACT_SET_DIRECTION",            2, {"TroopID", "Direction", ""}},
    {39, "ACT_SHOW_EFFECT",              3, {"EffectID", "X", "Y"}},
    {40, "ACT_SET_TROOP_SCALE",          2, {"TroopID", "Scale", ""}},
    {41, "ACT_CHANGE_LEADER_MODEL",      2, {"TroopID", "ModelID", ""}},
    {42, "ACT_SET_TROOP_HP",             2, {"TroopID", "Percent", ""}},
    {43, "ACT_SET_LEADER_HP",            2, {"TroopID", "Percent", ""}},
    {44, "ACT_SHOW_SUBTITLE",            2, {"SubtitleID", "Duration", ""}},
    {45, "ACT_HIDE_UI",                  0, {"", "", ""}},
    {46, "ACT_SHOW_UI",                  0, {"", "", ""}},
    {47, "ACT_SET_MINIMAP_VISIBLE",      1, {"Visible", "", ""}},
    {48, "ACT_LOCK_CAMERA",              0, {"", "", ""}},
    {49, "ACT_UNLOCK_CAMERA",            0, {"", "", ""}},
    {50, "ACT_FADE_IN",                  1, {"Duration", "", ""}},
    {51, "ACT_FADE_OUT",                 1, {"Duration", "", ""}},
    {52, "ACT_SET_TROOP_NUM",            2, {"TroopID", "Count", ""}},
    {53, "ACT_SET_OBJECT_HP",            2, {"ObjectID", "HP", ""}},
    {54, "ACT_SET_TIME_LIMIT",           1, {"Seconds", "", ""}},
    {55, "ACT_VAR_INT_SET",              2, {"VariableID", "Value", ""}},
    {56, "ACT_VAR_INT_ADD",              2, {"VariableID", "Value", ""}},
    {57, "ACT_SHOW_OBJECTIVE",           1, {"ObjectiveID", "", ""}},
    {58, "ACT_HIDE_OBJECTIVE",           1, {"ObjectiveID", "", ""}},
    {59, "ACT_COMPLETE_OBJECTIVE",       1, {"ObjectiveID", "", ""}},
    {60, "ACT_PLAY_VOICE",              1, {"VoiceID", "", ""}},
    {61, "ACT_SET_ALLY_CONTROL",         2, {"TroopID", "Control", ""}},
    {62, "ACT_FORCE_RETREAT",            1, {"TroopID", "", ""}},
    {63, "ACT_DISABLE_RETREAT",          1, {"TroopID", "", ""}},
    {64, "ACT_ENABLE_RETREAT",           1, {"TroopID", "", ""}},
    {65, "ACT_CHANGE_TROOP_TYPE",        2, {"TroopID", "TypeID", ""}},
    {66, "ACT_SET_OBJECT_VISIBLE",       2, {"ObjectID", "Visible", ""}},
    {67, "ACT_PLAY_ANIMATION",           2, {"TroopID", "AnimID", ""}},
    {68, "ACT_SET_INVULNERABLE_TIME",    2, {"TroopID", "Seconds", ""}},
    {69, "ACT_EARTHQUAKE",               2, {"Duration", "Intensity", ""}},
    {70, "ACT_SET_FOG",                  1, {"FogID", "", ""}},
    {71, "ACT_SET_OBJECT_TEAM",          2, {"ObjectID", "TeamID", ""}},
    {72, "ACT_SHOW_TIMER",              1, {"Seconds", "", ""}},
    {73, "ACT_HIDE_TIMER",              0, {"", "", ""}},
    {74, "ACT_SET_LEADER_LEVEL",         2, {"TroopID", "Level", ""}},
    {75, "ACT_ADD_TROOP_EXP",            2, {"TroopID", "EXP", ""}},
    {76, "ACT_SET_ATTACK_RANGE",         2, {"TroopID", "Range", ""}},
    {77, "ACT_TELEPORT_TROOP",           2, {"TroopID", "AreaID", ""}},
    {78, "ACT_SET_TROOP_VISIBLE",        2, {"TroopID", "Visible", ""}},
    {79, "ACT_PLAY_CUTSCENE",            1, {"CutsceneID", "", ""}},
    {80, "ACT_SET_LEADER_SKILL_LEVEL",   3, {"TroopID", "SkillSlot", "Level"}},
    {81, "ACT_GIVE_TROOP_ITEM",          2, {"TroopID", "ItemID", ""}},
    {82, "ACT_SET_TROOP_FORMATION",      2, {"TroopID", "Formation", ""}},
    {83, "ACT_FORCE_ATTACK",             2, {"TroopID", "TargetID", ""}},
    {84, "ACT_TROOP_STOP",               1, {"TroopID", "", ""}},
    {85, "ACT_SET_LEADER_ANIM",          2, {"TroopID", "AnimID", ""}},
    {86, "ACT_SET_TROOP_MORALE",         2, {"TroopID", "Morale", ""}},
    {87, "ACT_TRIGGER_EVENT",            1, {"EventID", "", ""}},
    {88, "ACT_SET_LEADER_AI",            2, {"TroopID", "AIID", ""}},
    {89, "ACT_CHANGE_BGM",               1, {"BGMID", "", ""}},
    {90, "ACT_LEADER_INVULNERABLE",      1, {"TroopID", "", ""}},
    {91, "ACT_LEADER_VULNERABLE",        1, {"TroopID", "", ""}},
    {92, "ACT_SET_WEATHER_INTENSITY",    1, {"Intensity", "", ""}},
    {93, "ACT_SHOW_AREA_EFFECT",         2, {"AreaID", "EffectID", ""}},
    {94, "ACT_HIDE_AREA_EFFECT",         1, {"AreaID", "", ""}},
    {95, "ACT_SET_OBJECT_ANIM",          2, {"ObjectID", "AnimID", ""}},
    {96, "ACT_REMOVE_ALL_ITEMS",         1, {"TroopID", "", ""}},
    {97, "ACT_SHOW_AREA_ON_MINIMAP",     1, {"AreaID", "", ""}},
    {98, "ACT_HIDE_AREA_ON_MINIMAP",     1, {"AreaID", "", ""}},
    {99, "ACT_SET_LEADER_WEAPON",        2, {"TroopID", "WeaponID", ""}},
    {100, "ACT_SET_LEADER_ARMOR",        2, {"TroopID", "ArmorID", ""}},
    {101, "ACT_SET_LEADER_ACCESSORY",    2, {"TroopID", "AccessoryID", ""}},
    {102, "ACT_ADD_OFFICER",             2, {"TroopID", "OfficerID", ""}},
    {103, "ACT_REMOVE_OFFICER",          2, {"TroopID", "OfficerSlot", ""}},
    {104, "ACT_SET_OFFICER_LEVEL",       3, {"TroopID", "OfficerSlot", "Level"}},
    {105, "ACT_SET_TROOP_MAX_HP",        2, {"TroopID", "MaxHP", ""}},
    {106, "ACT_SET_LEADER_MAX_HP",       2, {"TroopID", "MaxHP", ""}},
    {145, "ACT_TROOP_SET_INVULNERABLE",  1, {"TroopID", "", ""}},
    {146, "ACT_TROOP_SET_VULNERABLE",    1, {"TroopID", "", ""}},
};

inline constexpr size_t kConditionCount = sizeof(kConditions) / sizeof(kConditions[0]);
inline constexpr size_t kActionCount = sizeof(kActions) / sizeof(kActions[0]);

const ScriptEntryInfo* findConditionInfo(uint32_t id);
const ScriptEntryInfo* findActionInfo(uint32_t id);

} // namespace kuf
