#pragma once

#include <cstddef>
#include <cstdint>

namespace kuf {

struct ScriptEntryInfo {
	uint32_t id;
	const char *name;
	uint32_t paramCount;
	const char *paramNames[3];
};

// Condition IDs from CruMission.h (authoritative game source).
// Gaps (16, 21) are unused in the game engine.
inline constexpr ScriptEntryInfo kConditions[] = {
    {0, "CON_TIME_ELAPSED", 2, {"Seconds", "Compare", ""}},
    {1,
     "CON_TIME_ELAPSED_FROM_MARKED",
     3,
     {"TimeMarkID", "Seconds", "Compare"}},
    {2, "CON_TROOP_IN_AREA", 2, {"TroopID", "AreaID", ""}},
    {3, "CON_TROOP_SCOUTER_STOPPED_IN_AREA", 2, {"TroopID", "AreaID", ""}},
    {4, "CON_TROOP_SCOUTER_IN_AREA", 2, {"TroopID", "AreaID", ""}},
    {5,
     "CON_TROOP_SCOUTER_CLOSE_TO_TROOP",
     3,
     {"TroopID", "TroopID2", "Distance"}},
    {6, "CON_TROOP_CLOSE_TO_TROOP", 3, {"TroopID", "TroopID2", "Distance"}},
    {7, "CON_TROOP_TARGETED", 2, {"TroopID", "PlayerID", ""}},
    {8, "CON_TROOP_ATTACKED", 1, {"TroopID", "", ""}},
    {9, "CON_TROOP_MELEE_ATTACKED", 1, {"TroopID", "", ""}},
    {10, "CON_TROOP_ABILITY", 2, {"TroopID", "AbilityID", ""}},
    {11, "CON_TROOP_WITH_THE_SUN_IN_BACK", 2, {"TroopID", "Value", ""}},
    {12, "CON_LEADER_HAS_BEEN_KILLED", 1, {"TroopID", "", ""}},
    {13, "CON_STATE_HP_PERCENT", 3, {"TroopID", "Percent", "Compare"}},
    {14, "CON_LEADER_HP", 3, {"TroopID", "Percent", "Compare"}},
    {15, "CON_OBJECT_LOCATED", 2, {"AreaID", "ObjectType", ""}},
    {17, "CON_OBJECT_HP_PERCENT", 3, {"ObjectID", "Percent", "Compare"}},
    {18, "CON_OBJECT_DETECTED", 1, {"ObjectType", "", ""}},
    {19, "CON_VAR", 3, {"VariableID", "Value", "Compare"}},
    {20, "CON_PLAYER_TROOP_ALL_DISABLED", 2, {"PlayerID", "Percent", ""}},
    {22, "CON_PLAYER_ALL_IN_AREA", 2, {"PlayerID", "AreaID", ""}},
    {23, "CON_TROOP_NOT_IN_AREA", 2, {"TroopID", "AreaID", ""}},
    {24, "CON_TROOP_ATTACKED_TROOP", 2, {"TroopID", "TargetID", ""}},
    {25, "CON_PLAYER_TROOP_NOT_IN_AREA", 2, {"AreaID", "PlayerID", ""}},
    {26, "CON_PLAYER_TROOP_IN_AREA", 2, {"AreaID", "PlayerID", ""}},
    {27, "CON_ALWAYS_TRUE", 0, {"", "", ""}},
    {28, "CON_PLAYER_KO", 1, {"PlayerID", "", ""}},
    {29, "CON_SCOUTER_BACK", 1, {"TroopID", "", ""}},
    {30, "CON_TROOP_IN_SIGHT", 1, {"TroopID", "", ""}},
    {31, "CON_TROOP_TYPE", 2, {"TroopID", "TroopType", ""}},
    {32, "CON_TROOP_TYPE_IN_AREA", 3, {"PlayerID", "TroopType", "AreaID"}},
    {33, "CON_TROOP_NOT_ENGAGED", 1, {"TroopID", "", ""}},
    {34, "CON_PLAYER_HP_SUM", 3, {"PlayerID", "Percent", "Compare"}},
    {35, "CON_GOT_FIRE", 1, {"AreaID", "", ""}},
    {36, "CON_CAM_DIR", 1, {"AreaID", "", ""}},
    {37, "CON_IS_DEMO_SKIPPED", 0, {"", "", ""}},
    {38, "CON_IS_MINE_AT", 2, {"PlayerID", "AreaID", ""}},
    {39, "CON_IS_TRAP_AT", 2, {"PlayerID", "AreaID", ""}},
    {40, "CON_TROOP_LEADER_TARGET_PLAYER", 1, {"TroopID", "", ""}},
    {41, "CON_PLAYER_ATTACKED", 1, {"PlayerID", "", ""}},
    {42, "CON_DAM_OPENED", 0, {"", "", ""}},
    {43, "CON_PLAYER_IN_SIGHT", 1, {"PlayerID", "", ""}},
    {44, "CON_RANGE_TROOP_IN_AREA", 2, {"AreaID", "PlayerID", ""}},
    {45, "CON_PLAYER_CLOSE_TO_TROOP", 3, {"PlayerID", "TroopID", "Distance"}},
    {46,
     "CON_PLAYER_CLOSE_TO_PLAYER",
     3,
     {"PlayerID", "PlayerID2", "Distance"}},
    {47, "CON_PLAYER_MELEE_ATTACKED", 1, {"PlayerID", "", ""}},
    {48, "CON_PLAYER_WITH_THE_SUN_IN_BACK", 1, {"PlayerID", "", ""}},
    {49, "CON_PLAYER_ATTACKED_TROOP", 2, {"PlayerID", "TroopID", ""}},
    {50, "CON_PLAYER_NOT_ENGAGED", 1, {"PlayerID", "", ""}},
    {51, "CON_TROOP_UNBLOCKABLE_ATTACKED", 1, {"TroopID", "", ""}},
    {52, "CON_TROOP_ABILITY_ATTACKED", 2, {"TroopID", "AbilityID", ""}},
    {53, "CON_IS_WATER_FLOODED_IN_AREA", 1, {"AreaID", "", ""}},
    {54, "CON_SP", 3, {"PlayerID", "Value", "Compare"}},
    {55, "CON_TROOP_SCALE", 2, {"TroopID", "ScaleType", ""}},
    {56, "CON_TROOP_ATTACKED_PLAYER", 2, {"TroopID", "PlayerID", ""}},
    {57, "CON_TROOP_ATTACKED_BY_FLOOD", 1, {"TroopID", "", ""}},
    {58, "CON_TROOP_ATTACK_WITH_FACING_THE_SUN", 1, {"TroopID", "", ""}},
    {59, "CON_PLAYER_SCOUTER_IS_NOT_IN_AREA", 2, {"PlayerID", "AreaID", ""}},
    {60, "CON_SELECTED_TROOP", 1, {"TroopID", "", ""}},
};

// Action IDs from CruMission.h (authoritative game source).
// Gaps (25, 30-31, 36-37, 40-46, 48, 69, 134, 156) are unused.
inline constexpr ScriptEntryInfo kActions[] = {
    {0, "ACT_TRIGGER_ACTIVATE", 1, {"TriggerID", "", ""}},
    {1, "ACT_TRIGGER_DEACTIVATE", 1, {"TriggerID", "", ""}},
    {2, "ACT_MARK_ON_TIME", 1, {"TimeMarkID", "", ""}},
    {3, "ACT_POINT_SHOW_IN_MINIMAP", 1, {"AreaID", "", ""}},
    {4, "ACT_POINT_HIDE_IN_MINIMAP", 1, {"AreaID", "", ""}},
    {5, "ACT_TROOP_INDICATE_IN_MINIMAP", 1, {"TroopID", "", ""}},
    {6, "ACT_CHAR_SAY", 2, {"CharID", "TextID", ""}},
    {7, "ACT_TROOP_SET_PARAM", 3, {"TroopID", "Param", "Value"}},
    {8, "ACT_TROOP_ENABLE", 1, {"TroopID", "", ""}},
    {9, "ACT_TROOP_DISABLE", 1, {"TroopID", "", ""}},
    {10, "ACT_TROOP_WALK_TO", 2, {"TroopID", "AreaID", ""}},
    {11, "ACT_TROOP_RUN_TO", 2, {"TroopID", "AreaID", ""}},
    {12, "ACT_TROOP_ADD_WAYPOINT", 3, {"TroopID", "AreaID", "MoveType"}},
    {13, "ACT_TROOP_FOLLOW", 3, {"TroopID", "TargetID", "Distance"}},
    {14, "ACT_TROOP_STOP", 1, {"TroopID", "", ""}},
    {15, "ACT_CAM_SET", 2, {"CameraID", "Duration", ""}},
    {16, "ACT_CAM_FORCE", 2, {"CameraID", "Duration", ""}},
    {17, "ACT_TROOP_RETREAT_TO", 2, {"TroopID", "AreaID", ""}},
    {18, "ACT_TROOP_ATTACK", 2, {"TroopID", "TargetID", ""}},
    {19, "ACT_TROOP_SET_TRAP", 2, {"TroopID", "TrapTypeID", ""}},
    {20, "ACT_TROOP_MORALE_UP", 1, {"TroopID", "", ""}},
    {21, "ACT_SET_CURSOR_POS", 1, {"AreaID", "", ""}},
    {22, "ACT_RESET_ALL_TRIGGERS", 0, {"", "", ""}},
    {23, "ACT_ADD_SP", 2, {"PlayerID", "SP", ""}},
    {24, "ACT_RIVER_FLOODED", 0, {"", "", ""}},
    {26, "ACT_TROOP_ABILITY", 3, {"TroopID", "AbilityID", "AreaID"}},
    {27, "ACT_TROOP_ABILITY_TO_TROOP", 3, {"TroopID", "AbilityID", "TargetID"}},
    {28, "ACT_TROOP_ATTACK_LEADER", 2, {"TroopID", "TargetID", ""}},
    {29, "ACT_HIDE_VAR", 0, {"", "", ""}},
    {32, "ACT_VAR_INCREASE", 2, {"VariableID", "Value", ""}},
    {33, "ACT_VAR_DISPLAY", 3, {"VariableID", "Value", "TextID"}},
    {34, "ACT_SHOW_SKIPPING_MESSAGE", 1, {"Visible", "", ""}},
    {35, "ACT_TROOP_ANNIHILATED", 1, {"TroopID", "", ""}},
    {38, "ACT_OPEN_SESAME", 1, {"PropID", "", ""}},
    {39, "ACT_CLOSE_SESAME", 1, {"PropID", "", ""}},
    {47, "ACT_EVENT_ANCIENT_HEART_CALLED_ME", 0, {"", "", ""}},
    {49, "ACT_MISSION_COMPLETE", 0, {"", "", ""}},
    {50, "ACT_MISSION_FAIL", 0, {"", "", ""}},
    {51, "ACT_DELAY_TICK", 1, {"Ticks", "", ""}},
    {52, "ACT_LOOP", 0, {"", "", ""}},
    {53, "ACT_RESET_TRIGGER", 0, {"", "", ""}},
    {54, "ACT_SHOW_TEXT", 1, {"TextID", "", ""}},
    {55, "ACT_VAR_INT_SET", 2, {"VariableID", "Value", ""}},
    {56, "ACT_VAR_RANDOM_SET", 2, {"VariableID", "Value", ""}},
    {57, "ACT_CAM_RESET", 0, {"", "", ""}},
    {58, "ACT_LETTER_BOX_ENABLE", 0, {"", "", ""}},
    {59, "ACT_LETTER_BOX_DISABLE", 0, {"", "", ""}},
    {60, "ACT_SHOW_TEXT_EX", 2, {"TextID", "Duration", ""}},
    {61, "ACT_RESET_TRIGGER_EX", 1, {"TriggerID", "", ""}},
    {62, "ACT_TROOP_SIGNAL", 2, {"TroopID", "AnimationID", ""}},
    {63, "ACT_BLOCK_AREA", 1, {"AreaID", "", ""}},
    {64, "ACT_OPEN_AREA", 1, {"AreaID", "", ""}},
    {65, "ACT_RECOVER_AREA", 1, {"AreaID", "", ""}},
    {66, "ACT_SET_AI", 2, {"TroopID", "AIID", ""}},
    {67, "ACT_ENABLE_AI", 1, {"TroopID", "", ""}},
    {68, "ACT_DISABLE_AI", 1, {"TroopID", "", ""}},
    {70, "ACT_SHOW_TEXT_XY_2", 3, {"X", "Y", "Duration"}},
    {71, "ACT_SET_SNOW", 1, {"Amount", "", ""}},
    {72, "ACT_REMOVE_SNOW", 0, {"", "", ""}},
    {73, "ACT_SET_CAM_TARGET", 1, {"TroopID", "", ""}},
    {74, "ACT_UNSET_CAM_TARGET", 0, {"", "", ""}},
    {75, "ACT_RENEW_TROOP", 1, {"TroopID", "", ""}},
    {76, "ACT_SHOW_TITLE", 3, {"X", "Y", "Duration"}},
    {77, "ACT_SHOW_TEXT_XY", 3, {"X", "Y", "Duration"}},
    {78, "ACT_SET_FPS", 1, {"FPS", "", ""}},
    {79, "ACT_RESET_FPS", 0, {"", "", ""}},
    {80, "ACT_SET_MOTION_BLUR", 1, {"Amount", "", ""}},
    {81, "ACT_RESET_MOTION_BLUR", 0, {"", "", ""}},
    {82, "ACT_TROOP_SET_SPEED", 2, {"TroopID", "Speed", ""}},
    {83, "ACT_TROOP_RESET_SPEED", 1, {"TroopID", "", ""}},
    {84, "ACT_SET_RAIN", 1, {"Amount", "", ""}},
    {85, "ACT_STOP_RAIN", 0, {"", "", ""}},
    {86, "ACT_SET_WIND", 2, {"Direction", "Strength", ""}},
    {87, "ACT_SET_GATE", 3, {"AreaID", "PlayerID", "Enable"}},
    {88, "ACT_START_WATER_ATTACK", 0, {"", "", ""}},
    {89, "ACT_CHAR_SAY_EX", 3, {"CharID", "TextID", "Duration"}},
    {90, "ACT_LEADER_INVULNERABLE", 1, {"TroopID", "", ""}},
    {91, "ACT_LEADER_VULNERABLE", 1, {"TroopID", "", ""}},
    {92, "ACT_LEADER_RECHARE_RATE", 2, {"TroopID", "Rate", ""}},
    {93, "ACT_TROOP_SET_BOUNDARY", 2, {"TroopID", "AreaID", ""}},
    {94, "ACT_TROOP_RESET_BOUNDARY", 1, {"TroopID", "", ""}},
    {95, "ACT_TROOP_WARP", 3, {"TroopID", "AreaID", "Direction"}},
    {96, "ACT_MY_PLAYER_GET_EXP", 1, {"EXP", "", ""}},
    {97, "ACT_SHOW_AREA_ON_MINIMAP", 1, {"AreaID", "", ""}},
    {98, "ACT_HIDE_AREA_ON_MINIMAP", 1, {"AreaID", "", ""}},
    {99, "ACT_SHOW_TEXT_ON_MSG_WINDOW", 3, {"TextID", "Duration", "Sound"}},
    {100, "ACT_TROOP_SIGNAL_ARROW", 2, {"TroopID", "AreaID", ""}},
    {101, "ACT_FADE_IN", 1, {"Duration", "", ""}},
    {102, "ACT_FADE_OUT", 1, {"Duration", "", ""}},
    {103, "ACT_OPEN_DAM", 0, {"", "", ""}},
    {104, "ACT_CLOSE_DAM", 0, {"", "", ""}},
    {105, "ACT_DISABLE_TROOPS_INSIDE_AREA", 2, {"AreaID", "PlayerID", ""}},
    {106, "ACT_DISABLE_TROOPS_OUTSIDE_AREA", 2, {"AreaID", "PlayerID", ""}},
    {107, "ACT_DISABLE_ALL_TROOPS", 0, {"", "", ""}},
    {108, "ACT_SET_DUMMY_TROOP_OBSTACLE_RADIUS", 2, {"Index", "Radius", ""}},
    {109, "ACT_COLLAPSE_WALL", 1, {"Index", "", ""}},
    {110, "ACT_PLAY_BGM", 3, {"Filename", "BGMID", "Repeat"}},
    {111, "ACT_STOP_BGM", 1, {"BGMID", "", ""}},
    {112, "ACT_START_TROOP_INDICATE_IN_MINIMAP", 1, {"TroopID", "", ""}},
    {113, "ACT_STOP_TROOP_INDICATE_IN_MINIMAP", 1, {"TroopID", "", ""}},
    {114, "ACT_TROOP_REFILL_HP", 1, {"TroopID", "", ""}},
    {115, "ACT_TROOP_SET_HP", 2, {"TroopID", "Percent", ""}},
    {116, "ACT_LIP_SYNC_BEGIN", 2, {"TroopID", "Slot", ""}},
    {117, "ACT_LIP_SYNC_END", 2, {"TroopID", "Slot", ""}},
    {118, "ACT_SET_FIRE_SPREAD_SPEED", 1, {"Speed", "", ""}},
    {119, "ACT_ENABLE_INPUT", 0, {"", "", ""}},
    {120, "ACT_DISABLE_INPUT", 0, {"", "", ""}},
    {121, "ACT_ENABLE_FOG_OF_WAR", 1, {"Enable", "", ""}},
    {122, "ACT_SET_FIRE_SPREAD_RANGE", 1, {"Range", "", ""}},
    {123, "ACT_SET_FIRE", 1, {"AreaID", "", ""}},
    {124, "ACT_REGNIER_GO_CRAZY", 1, {"TroopID", "", ""}},
    {125, "ACT_REGNIER_FREE_HIS_POWER", 1, {"TroopID", "", ""}},
    {126, "ACT_SET_MUTE", 1, {"Mute", "", ""}},
    {127, "ACT_BURY_TROOP", 1, {"TroopID", "", ""}},
    {128, "ACT_OFFICER_SAY", 2, {"CharID", "TextID", ""}},
    {129, "ACT_TAG_THE_TROOP", 2, {"TroopID", "Tag", ""}},
    {130, "ACT_UNTAG_THE_TROOP", 1, {"TroopID", "", ""}},
    {131, "ACT_SHOW_VAR_GAUGE", 3, {"PortraitID", "VariableID", "TextID"}},
    {132, "ACT_HIDE_VAR_GAUGE", 0, {"", "", ""}},
    {133, "ACT_TROOP_ANIMATION", 2, {"TroopID", "AnimationID", ""}},
    {135, "ACT_TROOP_RANGE_ATTACK_ON_POS", 2, {"TroopID", "AreaID", ""}},
    {136, "ACT_TROOP_RANGE_ATTACK_ON_PROP", 2, {"TroopID", "PropID", ""}},
    {137, "ACT_SET_AI_PATH", 2, {"PathID", "AreaID", ""}},
    {138, "ACT_ENABLE_ABILITY", 1, {"AbilityID", "", ""}},
    {139, "ACT_DISABLE_ABILITY", 1, {"AbilityID", "", ""}},
    {140, "ACT_SHOW_NOISE_METER_GAUGE", 1, {"TextID", "", ""}},
    {141, "ACT_SET_BGM_VOLUME", 2, {"BGMID", "Percent", ""}},
    {142, "ACT_FADE_BGM", 3, {"BGMID", "Ticks", "Percent"}},
    {143, "ACT_MARK_ON_TROOP_IN_AREA", 3, {"AreaID", "PlayerID", "Ticks"}},
    {144, "ACT_SET_WALL_HP", 2, {"PropID", "HP", ""}},
    {145, "ACT_TROOP_SET_INVULNERABLE", 1, {"TroopID", "", ""}},
    {146, "ACT_TROOP_RESET_INVULNERABLE", 1, {"TroopID", "", ""}},
    {147, "ACT_TROOP_SELECT", 1, {"TroopID", "", ""}},
    {148, "ACT_FORCE_MINIMAP_ON", 0, {"", "", ""}},
    {149, "ACT_FORCE_MINIMAP_OFF", 0, {"", "", ""}},
    {150, "ACT_SHOW_PROP_HP_GAUGE", 2, {"TextID", "PropID", ""}},
    {151, "ACT_SHOW_TROOP_HP_GAUGE", 2, {"TextID", "TroopID", ""}},
    {152, "ACT_RENEW_TROOP_OUTOFSIGHT", 3, {"TroopID", "AreaID", "PlayerID"}},
    {153, "ACT_SET_TRAP", 3, {"AreaID", "PlayerID", "Count"}},
    {154, "ACT_SET_MINE", 3, {"AreaID", "PlayerID", "Count"}},
    {155, "ACT_FLOOD_RESET", 0, {"", "", ""}},
    {157, "ACT_ENABLE_PAUSE", 0, {"", "", ""}},
    {158, "ACT_DISABLE_PAUSE", 0, {"", "", ""}},
    {159, "ACT_QUICK_SAVE", 0, {"", "", ""}},
    {160, "ACT_CHAR_RANDOM_SAY", 2, {"PortraitID", "TextID", ""}},
    {161, "ACT_ENABLE_TROOP_IN_AREA", 2, {"AreaID", "PlayerID", ""}},
    {162, "ACT_PLAYER_TROOP_STOP", 1, {"PlayerID", "", ""}},
    {163, "ACT_EXCLUSIVE_BEGIN", 0, {"", "", ""}},
    {164, "ACT_EXCLUSIVE_END", 0, {"", "", ""}},
    {165, "ACT_LOAD_MISSION", 2, {"Filename", "Mode", ""}},
    {166, "ACT_JOYPAD_RUMBLE", 1, {"Enable", "", ""}},
    {167, "ACT_SHOW_TROOP_DIST_GAUGE", 2, {"PortraitID", "TextID", ""}},
    {168, "ACT_SET_FIRE_N_SMOKE", 2, {"AreaID", "Count", ""}},
    {169, "ACT_SET_WATER_EFFECT_PROP", 1, {"AreaID", "", ""}},
    {170, "ACT_SET_SCREEN_GLOW", 1, {"Enable", "", ""}},
    {171, "ACT_UPDATE_UNIT_KILL_COUNT", 2, {"VariableID", "PlayerID", ""}},
    {172, "ACT_PLAY_FMV", 2, {"Filename", "NextMission", ""}},
    {173, "ACT_ENABLE_LENS_FLARE", 1, {"Enable", "", ""}},
    {174, "ACT_CHANGE_SKYBOX_N_LIGHT_SET", 2, {"Skybox", "LightSet", ""}},
    {175, "ACT_REMOVE_TRAP", 2, {"AreaID", "PlayerID", ""}},
    {176, "ACT_SET_FIRE_N_SMOKE_SMALL", 2, {"AreaID", "Count", ""}},
    {177, "ACT_SET_TRAINING_MISSION", 2, {"Slot", "Enable", ""}},
    {178, "ACT_SET_LIBRARY", 2, {"Slot", "Enable", ""}},
    {179, "ACT_ALL_MISSION_COMPLETE", 0, {"", "", ""}},
    {180, "ACT_PLAY_FMV_AND_GO_TO_WORLDMAP", 1, {"Filename", "", ""}},
    {181, "ACT_GO_TO_WORLDMAP", 0, {"", "", ""}},
    {182, "ACT_SKIP_TEXT", 0, {"", "", ""}},
};

inline constexpr size_t kConditionCount =
    sizeof(kConditions) / sizeof(kConditions[0]);
inline constexpr size_t kActionCount = sizeof(kActions) / sizeof(kActions[0]);

const ScriptEntryInfo *findConditionInfo(uint32_t id);
const ScriptEntryInfo *findActionInfo(uint32_t id);

} // namespace kuf
